name: tests

on:
  push:
    branches:
      - main
    tags: ['v[0-9]*', '[0-9]+.[0-9]+*']
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  precommit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: pre-commit/action@v3.0.0

  unit-tests:
    needs: precommit-hooks
    strategy:
      matrix:
        python-version: ['3.8'] #, '3.9', '3.10']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev, orbit, sktime, statsforecast, pyod]"

    - name: Run unit tests
      run: |
        echo "Running pytest"
        pytest

  examples:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev, orbit, sktime, statsforecast, pyod]"

    - name: Run examples
      run: |
        echo "Running Orbit example"
        python examples/orbit/train.py

        echo "Running Sktime example"
        python examples/sktime/train.py

        echo "Running StatsForecast example"
        python examples/statsforecast/train.py

        echo "Running PyOD example"
        python examples/pyod/train.py

  documentation:
    needs: examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"

    - name: Build documentation
      run: |
        echo "Building documentation"
        cd docs
        make clean
        make html

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: sphinx
        path: docs/build/html
