name: Release

on:
  release:
    types:
      - published

jobs:
  build_wheel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build wheel
        run: |
          python -m pip install build
          python -m build

      - name: Store wheel files
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*

  pypi-publish:
    runs-on: ubuntu-latest
    needs: build_wheels
    environment:
      name: pypi
      url: https://pypi.org/p/mlflavors

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
