name: Release

on:
  release:
    types:
      - published

jobs:
  build_wheel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build wheel
        run: |
          python -m pip install build
          python -m build

      - name: Store wheel files
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*

  test_wheel:
    needs: build_wheel
    name: Test wheels on ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8'] #, '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Get wheel filename
        run: echo "WHEELNAME=$(ls ./dist/mlflavors-*none-any.whl)" >> $GITHUB_ENV

      - name: Install wheel and extras
        run: |
          python -m pip install --upgrade pip
          python -m pip install "${{ env.WHEELNAME }}[dev]"

      - name: Run unit tests
        run: |
          echo "Running pytest"
          pytest

  pypi-publish:
    runs-on: ubuntu-latest
    needs: test_wheel
    environment:
      name: pypi
      url: https://pypi.org/p/mlflavors

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
